title: Sijin Sun
email: sun.sijin@u.nus.edu
description: >-
  Master Student in Maritime Technology and Management
  National University of Singapore
baseurl: ""
url: ""
twitter_username: ""
github_username: ""

# Build settings
markdown: kramdown
theme: jekyll-academic
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-scholar

# Include directories
include:
  - assets/images

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git
  - .gitignore 